### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juliocanares** [flashhawk/spp.js#2]
Hi amazing work! , a question, is there a documentation page? , thanks :D

**Comment by flashhawk** [comment]
Not yet, coming soon. Thank you

**Comment by juliocanares** [comment]
Perfect bro! :)

**Comment by crystal89** [comment]
Thanks!

------------------ 原始邮件 ------------------
发件人: "Julio Canares"notifications@github.com;
发送时间: 2013年7月15日(星期一) 凌晨5:20
收件人: "flashhawk/spp.js"spp.js@noreply.github.com; 

主题: [spp.js] Documentation (#2)

Hi amazing work! , a question, is there a documentation page? , thanks :D
